services:
  webapp:
    build: .
    image: img-perpus-indianajones
    container_name: perpus-laravel
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: perpusku_gc
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
